### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by rozling** [google/google-api-python-client#3] opened 2014-05-06 13:53 UTC
Request for Python 3 support (continuing on from https://code.google.com/p/google-api-python-client/issues/detail?id=57).  My use case is for using the popular editor Sublime Text 3 to interact with the Google API.

**Comment by cjerdonek** [comment] 2015-01-02 18:18
It would be good if the supported Python versions (i.e. non-support for Python 3) were properly documented (e.g. in the Trove classifiers in setup.py):

    https://github.com/google/google-api-python-client/blob/master/setup.py#L87

This message is also misleading:

    print('google-api-python-client requires python version >= 2.6.'

(from https://github.com/google/google-api-python-client/blob/master/setup.py#L25 )

**Comment by breezymri** [comment] 2015-01-08 01:44
+1 for python 3

**Comment by pferate** [comment] 2015-01-08 16:36
I've updated the codebase in my fork to work with both Python 2 and 3.  It still can be optimized more, but it is passing all of the tests in 2.6, 2.7, 3.3, and 3.4.

Hopefully my pull request will be reviewed and merged soon, there are a lot of changes.

**Comment by Julienh** [comment] 2015-01-18 12:57
+1 for Python 3 support.

**Comment by edutopy** [comment] 2015-01-19 22:20
+1 for Python 3 support.

**Comment by Bobspadger** [comment] 2015-01-21 16:46
yep, really need python3 support now folks!

**Comment by tommyjcarpenter** [comment] 2015-01-22 22:36
This thread makes me cry. I am deeply saddened that the google-api-python-client is only available for Python2. This really throws a wrench in the works of my new project.

**Comment by chhantyal** [comment] 2015-01-22 22:58
It's really sad that there are so many requests, but no response from @google about roadmap.

**Comment by troygrosfield** [comment] 2015-01-22 23:20
Maybe twitter is a better way to reach them?

- https://twitter.com/TroyGrosfield/status/558403437067382784

**Comment by cjerdonek** [comment] 2015-01-23 00:04
Is there any reason we can't consolidate around the most promising fork?  Is there one?

**Comment by llrs** [comment] 2015-02-02 09:02
Anyone tried with the [lib2to3](https://docs.python.org/2.7/library/2to3.html)? I am sure supported errors like these one are common:

```cmd
  File "C:\Python33\lib\site-packages\googleapiclient\discovery.py", line 208
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```
This line should be ```except ValueError as e:``` as lib2to3 automatically changes.

**Comment by methane** [comment] 2015-02-02 09:04
@llrs See https://github.com/google/google-api-python-client/pull/25

**Comment by NotSqrt** [comment] 2015-02-02 15:20
:+1:

**Comment by willmoy** [comment] 2015-02-07 21:45
Bit dumbfounded to find out I can't use Google APIs with Python 3 already, so adding my +1.

**Comment by hlwsmith** [comment] 2015-02-07 23:40
adding my +1 to this! Google does support py3.3+ in oauth2client, so why not here too?

**Comment by joyofdata** [comment] 2015-02-13 13:16
:+1:

**Comment by RandomInsano** [comment] 2015-02-15 05:02
+1. I'll experiment with @pferate's fork for now.

**Comment by JelteF** [comment] 2015-02-15 12:24
I've been using that one quite successfully. However, I only use the calendar functionality. Be sure to use the version of oauthclient mentioned in that thread.

**Comment by dandesousa** [comment] 2015-02-15 19:31
+1

**Comment by jackgolding** [comment] 2015-02-20 07:55
+1

**Comment by fsufitch** [comment] 2015-02-20 16:37
+1

**Comment by gijoecool** [comment] 2015-02-21 17:22
+1

**Comment by sloria** [comment] 2015-02-24 05:26
Big +1 to this.

**Comment by cnelson** [comment] 2015-03-04 00:44
+1

Hard to sell people on using good technologies like discovery documents when the tools aren't there to support them.

**Comment by meng-fu** [comment] 2015-03-05 00:44
+1

**Comment by methane** [comment] 2015-03-05 01:26
Please test #64 with your script instead of posting more +1.

**Comment by edutopy** [comment] 2015-03-05 04:25
@methan  How i can do those tests?

**Comment by methane** [comment] 2015-03-05 04:27
1. Checkout #64 and install it.
2. Run your program using google-api-python-client.

**Comment by cnelson** [comment] 2015-03-05 14:32
@methane I've been running my code under @pferate's fork for sometime now and it's working fine.

-Chris

**Comment by pferate** [comment] 2015-03-05 15:36
@cnelson I would recommend trying my python3-module_updates branch (the branch in #64).  There *should* be no difference with my python3 branch operationally.  I had to go and create a cleaner branch to get the code merged upstream.  The branch in #64 will hopefully be merged soon.

**Comment by cnelson** [comment] 2015-03-05 16:16
@pferate I just updated my packages to build against https://github.com/pferate/google-api-python-client/zipball/python3-module_updates#egg=google-api-python-client-1.3.2 and it still looks good.

It'll be great to see this merged in, thanks for all the work!

**Comment by nathanielmanistaatgoogle** [comment] 2015-03-10 17:19
I've just merged in cf939a33f6b8 which we believe makes google-api-python-client fully support Python 3. Please everyone try it out and let us know where and how we've created problems. :-)

**Comment by tommyjcarpenter** [comment] 2015-03-10 17:26
NATHANIELMANISTA +10000

**Comment by pferate** [comment] 2015-03-10 19:31
Feels good to finally have this taken care of.

Thanks for reviewing the code @nathanielmanistaatgoogle!  Also thanks to everyone else who helped out with this, including @craigcitro and @methane!

**Comment by tommyjcarpenter** [comment] 2015-03-10 19:32
File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/googleapiclient/discovery.py", line 208
    except ValueError, e:
                     ^
SyntaxError: invalid syntax

**Comment by nathanielmanistaatgoogle** [comment] 2015-03-10 19:34
@tommyjcarpenter: looks like that would be covered by either #44 or #61?

@methane, @pferate: looks like we missed a spot?

**Comment by pferate** [comment] 2015-03-10 19:38
@tommyjcarpenter: that error looks like it is from an older revision.  Please note that this hasn't been pushed outside of github yet (to my knowledge), so you will have to install this package manually for now.

**Comment by JelteF** [comment] 2015-03-10 19:45
You can use the trick from this comment: https://github.com/google/google-api-python-client/pull/45#issuecomment-70196973
Now that it's merged you can use this in your `requirements.txt` 
```
git+git://github.com/google/google-api-python-client@master#egg=google-api-python-client
```

**Comment by cnelson** [comment] 2015-03-10 20:19
FWIW, this looks solid to me across python 2 and python 3.  My test suite runs clean.

Any idea when we can expect to see this hit PyPI?

### Tox output
    py26: commands succeeded
    py27: commands succeeded
    py33: commands succeeded
    py34: commands succeeded
    flake8: commands succeeded
    congratulations :)

**Comment by tommyjcarpenter** [comment] 2015-03-10 20:21
Ahh, sorry, my fault! I pip3ed (which worked) without realizing this probably wasn't pushed into PyPi yet.

**Comment by pferate** [comment] 2015-03-10 20:26
Not sure when it will be pushed.  I created another PR (#67) to update some `setup.py` for PyPi, but it will be up to the Googlers to push it out.

**Comment by nathanielmanistaatgoogle** [comment] 2015-03-10 23:49
Python 3 support has now been pushed to PyPI as version 1.4.0 (https://pypi.python.org/pypi/google-api-python-client/1.4.0). Please everyone test away and report defects and mistakes back to us here?

**Comment by tommyjcarpenter** [comment] 2015-03-11 02:14
Here is a stacktrace I get with 1.4.0:

Traceback (most recent call last):
  File "src/main.py", line 99, in <module>
    main(sys.argv)
  File "src/main.py", line 60, in main
    service  = ga_connector.get_service_object('analytics', 'v3', flags, 'https://www.googleapis.com/auth/analytics.readonly')
  File "/Users/tcarpenter/Development/Eclipse/python2-research-google-api-exploration/connector/ga_connector.py", line 45, in get_service_object
    service = discovery.build(name, version, http=http)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/googleapiclient/discovery.py", line 196, in build
    resp, content = http.request(requested_url)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/oauth2client/client.py", line 547, in new_request
    redirections, connection_type)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/httplib2/__init__.py", line 1139, in request
    headers = self._normalize_headers(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/httplib2/__init__.py", line 1107, in _normalize_headers
    return _normalize_headers(headers)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/httplib2/__init__.py", line 195, in _normalize_headers
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/httplib2/__init__.py", line 195, in <listcomp>
    return dict([ (key.lower(), NORMALIZE_SPACE.sub(value, ' ').strip())  for (key, value) in headers.items()])
TypeError: sequence item 0: expected str instance, bytes found

**Comment by methane** [comment] 2015-03-11 03:01
@tommyjcarpenter See jcgregorio/httplib2#296

**Comment by tommyjcarpenter** [comment] 2015-03-11 12:21
@methane It looks like that was not yet pushed to PyPI. Latest install 0.9 still broken.

**Comment by kylegoetz** [comment] 2015-03-21 06:05
"No Python 3 Support" probably should be up front and center. I spent quite a while trying to figure out why installing with pip3 worked but the Google samples all failed on authorization. It's because clean_headers() that the docs says converts bytes to strings actually converts strings to bytes with Python 3!

**Comment by wldcordeiro** [comment] 2015-03-21 23:01
@kylegoetz Read this thread, Python 3 is supported but the package on PyPI isn't updated yet.

**Comment by kylegoetz** [comment] 2015-03-21 23:21
@wldcordeiro  Sorry, the issue is still marked as open, so I thought that meant the issue was not resolved.

In any case, this repo instructs you to install with pip, and installing with pip downloads a version for Python 2 even if you're using pip for Python 3. So the install instructions are not correct. That's all I was trying to say: should be corrected install instructions.

**Comment by tommyjcarpenter** [comment] 2015-03-21 23:43
Pip3 install from Google works now, if you install httplib2 from master from source first. That library is the one that hasn't yet been pushed to PyPi. I pip3ed the Google API without problems after installing that library. 

(On my phone, sorry for any typos)

**Comment by tmatsuo** [comment] 2015-04-13 17:34
Good news!
[httplib2 0.9.1](https://pypi.python.org/pypi/httplib2/0.9.1) is released and now it's working even if you get everything from PyPi.

**Comment by tommyjcarpenter** [comment] 2015-04-13 17:38
🎉😀👍

**Comment by wldcordeiro** [comment] 2015-04-13 17:44
This issue can be closed at this point.

**Comment by cjerdonek** [comment] 2015-04-20 13:00
> Please everyone test away and report defects and mistakes back to us here?

FYI, I'm having trouble sending e-mails with binary (PDF) attachments when using Python 3.4 (google-api-python-client version 1.4.0 and httplib2 version 0.9.1).  Issue filed [here](https://github.com/google/google-api-python-client/issues/93).

**Comment by nathanielmanistaatgoogle** [comment] 2015-04-20 15:08
This seems to be an overall success; closing this issue.

**Closed by nathanielmanistaatgoogle** 2015-04-20 15:08 UTC
Labels: enhancement

**Comment by xenomachina** [comment] 2015-05-09 00:31
This page still says only 2.6 and 2.7 are supported: https://developers.google.com/api-client-library/python/start/installation

**Comment by tmatsuo** [comment] 2015-05-09 00:39
@xenomachina Thanks! Filed an internal bug.

**Comment by wescpy** [comment] 2015-08-06 19:11
Bug fixed... the official docs now state 2.6, 2.7, 3.3, and 3.4 are supported. Python 3 users will probably use "pip3" instead of "pip".

**Comment by david-xie** [comment] 2015-08-07 04:25
Excellent!

---- 
Best Regards,
David Xie
Founder of ScriptFan technology community - http://scriptfan.com
Manager of Xi'an GDG (Google Developer Group) - http://gdgxian.org
http://about.me/davidx

-----------------
Everything happens for a reason. Attitude determines everything!

On 7 August, 2015 at 3:11:54 am, wesley chun (notifications@github.com) wrote:

Bug fixed... the official docs now state 2.6, 2.7, 3.3, and 3.4 are supported. Python 3 users will probably use "pip3" instead of "pip".
