### ISSUE TITLE
Update  "Sending e-mail" docs to work with Python 3

### ISSUE THREAD

**Issue by cjerdonek** [google/google-api-python-client#93] opened 2015-04-20 12:55 UTC
The documentation for sending e-mails doesn't seem to work when using Python 3.  Also, I can't seem to get e-mail sending working with Python 3 when sending binary (PDF) attachments.  The code I'm using worked with Python 2.  Details are below.

The Gmail REST API documentation for [sending e-mail](https://developers.google.com/gmail/api/guides/sending) says to do the following:

``` python
raw = base64.urlsafe_b64encode(mime.as_string())
body = {'raw': raw}
messages = service.users().messages()
message = messages.send(userId='me', body=body).execute()
```

However, this code results in the following error:

```
File "/Users/chris/dev/.virtualenvs/my_package/lib/python3.4/base64.py", line 121, in urlsafe_b64encode
  return b64encode(s).translate(_urlsafe_encode_translation)
File "/Users/chris/dev/.virtualenvs/my_package/lib/python3.4/base64.py", line 62, in b64encode
  encoded = binascii.b2a_base64(s)[:-1]
TypeError: 'str' does not support the buffer interface
```

Changing `as_string()` in the above to `as_bytes()`:

``` python
raw = base64.urlsafe_b64encode(mime.as_bytes())
body = {'raw': raw}
messages = service.users().messages()
message = messages.send(userId='me', body=body).execute()
```

results in the following error:

```
File "/Users/chris/dev/.virtualenvs/my_package/lib/python3.4/site-packages/googleapiclient/discovery.py", line 691, in method
  actual_path_params, actual_query_params, body_value)
File "/Users/chris/dev/.virtualenvs/my_package/lib/python3.4/site-packages/googleapiclient/model.py", line 149, in request
  body_value = self.serialize(body_value)
File "/Users/chris/dev/.virtualenvs/my_package/lib/python3.4/site-packages/googleapiclient/model.py", line 258, in serialize
  return json.dumps(body_value)
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 230, in dumps
  return _default_encoder.encode(obj)
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 192, in encode
  chunks = self.iterencode(o, _one_shot=True)
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 250, in iterencode
  return _iterencode(o, 0)
File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 173, in default
  raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'Q29ud...TY9PS0tCg==' is not JSON serializable
```

If I add `raw = raw.decode()` to ensure that `raw` is a string in Python 3 as opposed to bytes, then the e-mail does get sent.  However, the PDF attachment now seems to be corrupted:

``` python
raw = base64.urlsafe_b64encode(mime.as_bytes())
raw = raw.decode()
body = {'raw': raw}
messages = service.users().messages()
message = messages.send(userId='me', body=body).execute()
```

**Comment by cjerdonek** [comment] 2015-04-20 13:34
Okay, I got it working.  When adding attachments, I needed to add the second line as below:

```python
msg.set_payload(contents)
# Encode the payload using Base64.  This line is from here:
# https://docs.python.org/3/library/email-examples.html
encoders.encode_base64(msg)
```

This also needs to be updated in the docs for Python (see [here](https://developers.google.com/gmail/api/guides/sending#creating_messages_with_attachments)).  I'm not sure how the docs should handle documenting both Python 2 and Python 3.

**Comment by tmatsuo** [comment] 2015-04-20 14:03
FYI I encountered similar issue and my quick hack is:
https://github.com/GoogleCloudPlatform/cloud-pubsub-logging-python/blob/master/pubsub_logging/utils.py#L38

**Comment by vinayak-mehta** [comment] 2016-01-19 22:18
Thanks @cjerdonek!

**Comment by t0il3ts0ap** [comment] 2016-03-25 11:18
thankyou @cjerdonek for your research !

**Comment by joseph-whiting** [comment] 2016-08-19 11:45
Awesome fix @cjerdonek, thanks a lot

**Comment by fazerlicourice7** [comment] 2016-12-29 17:09
@cjerdonek You, are A SAVIOR!!!! Thank you so much!

**Comment by mhoffa** [comment] 2017-03-02 13:17
@cjerdonek Thank you so much!

**Comment by divinedragon** [comment] 2017-04-07 09:29
Just in case still faces an issue like me, here is my code.

```python
with open(file, 'rb') as pdf_file:
      pdf = MIMEBase('application', "pdf")
      pdf.set_payload(pdf_file.read())
      encoders.encode_base64(pdf)
      pdf.add_header('Content-Disposition', 'attachment', filename=os.path.basename(file))

message.attach(pdf)

return {'raw': base64.urlsafe_b64encode(message.as_bytes()).decode()}
```

**Comment by zamai** [comment] 2017-06-03 11:09
Wow, 2 years passed since  Apr 20, 2015. But I'm still running into the same issue.
Maybe it's time to update docs? 
Thanks, @cjerdonek for your initial investigation and @divinedragon for the example.

**Comment by gmarchi** [comment] 2017-09-27 08:34
Still same issue in 2017! Thank you so much @cjerdonek

**Comment by luabr** [comment] 2017-10-05 20:07
Still same issue in October 2017!

here is a full working script for sending messages with attatchments (you just need to fill out the arguments for create_message_with_attatchment):

`from __future__ import print_function
import httplib2

from email.encoders import encode_base64
from apiclient import discovery
from oauth2client import client
from oauth2client import tools
from oauth2client.file import Storage
import base64
from email.mime.audio import MIMEAudio
from email.mime.base import MIMEBase
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import mimetypes
import os

from apiclient import errors


try:
    import argparse
    flags = argparse.ArgumentParser(parents=[tools.argparser]).parse_args()
except ImportError:
    flags = None

# If modifying these scopes, delete your previously saved credentials
# at ~/.credentials/gmail-python-quickstart.json
SCOPES = 'https://mail.google.com/'
CLIENT_SECRET_FILE = 'client_id.json'
APPLICATION_NAME = 'Gmail API Python Quickstart'


def get_credentials():
    """Gets valid user credentials from storage.

    If nothing has been stored, or if the stored credentials are invalid,
    the OAuth2 flow is completed to obtain the new credentials.

    Returns:
        Credentials, the obtained credential.
    """
    home_dir = os.path.expanduser('~')
    credential_dir = os.path.join(home_dir, '.credentials')
    if not os.path.exists(credential_dir):
        os.makedirs(credential_dir)
    credential_path = os.path.join(credential_dir,
                                   'gmail-python-quickstart.json')

    store = Storage(credential_path)
    credentials = store.get()
    if not credentials or credentials.invalid:
        flow = client.flow_from_clientsecrets(CLIENT_SECRET_FILE, SCOPES)
        flow.user_agent = APPLICATION_NAME
        if flags:
            credentials = tools.run_flow(flow, store, flags)
        else: # Needed only for compatibility with Python 2.6
            credentials = tools.run(flow, store)
        print('Storing credentials to ' + credential_path)
    return credentials


def CreateMessage(sender, to, subject, message_text):
  """Create a message for an email.

  Args:
    sender: Email address of the sender.
    to: Email address of the receiver.
    subject: The subject of the email message.
    message_text: The text of the email message.

  Returns:
    An object containing a base64url encoded email object.
  """
  message = MIMEText(message_text)
  message['to'] = to
  message['from'] = sender
  message['subject'] = subject
  return {'raw': base64.urlsafe_b64encode(message.as_string().encode('UTF-8')).decode('ascii')}


def create_message_with_attachment(
    sender, to, subject, message_text, file):
  """Create a message for an email.

  Args:
    sender: Email address of the sender.
    to: Email address of the receiver.
    subject: The subject of the email message.
    message_text: The text of the email message.
    file: The path to the file to be attached.

  Returns:
    An object containing a base64url encoded email object.
  """
  message = MIMEMultipart()
  message['to'] = to
  message['from'] = sender
  message['subject'] = subject

  msg = MIMEText(message_text)
  message.attach(msg)

  content_type, encoding = mimetypes.guess_type(file)
  print(content_type)
  if content_type is None or encoding is not None:
    content_type = 'application/octet-stream'
  main_type, sub_type = content_type.split('/', 1)
  print(main_type)
  print(sub_type)
  if main_type == 'text':
    fp = open(file, 'rb')
    msg = MIMEText(fp.read(), _subtype=sub_type)
    fp.close()
  elif main_type == 'image':
    fp = open(file, 'rb')
    msg = MIMEImage(fp.read(), _subtype=sub_type)
    fp.close()
  elif main_type == 'audio':
    fp = open(file, 'rb')
    msg = MIMEAudio(fp.read(), _subtype=sub_type)
    fp.close()
  # elif sub_type == 'pdf':
  #     with open(file, 'rb') as f:
  #         msg = MIMEBase('application', "pdf")
  #         msg.set_payload(f.read())
  #         encode_base64(msg)
  #         msg.add_header('Content-Disposition', 'attachment', filename=os.path.basename(file))
  else:
    fp = open(file, 'rb')
    msg = MIMEBase(main_type, sub_type)
    msg.set_payload(fp.read())
    encode_base64(msg)
    msg.add_header('Content-Disposition', 'attachment', filename=os.path.basename(file))
    fp.close()
  filename = os.path.basename(file)
  msg.add_header('Content-Disposition', 'attachment', filename=filename)

  message.attach(msg)

  return {'raw': base64.urlsafe_b64encode(message.as_string().encode('UTF-8')).decode('ascii')}

def SendMessage(service, user_id, message):
  """Send an email message.

  Args:
    service: Authorized Gmail API service instance.
    user_id: User's email address. The special value "me"
    can be used to indicate the authenticated user.
    message: Message to be sent.

  Returns:
    Sent Message.
  """
  try:
    message = (service.users().messages().send(userId=user_id, body=message)
               .execute())
    print('Message Id: %s' % message['id'])
    return message
  except errors.HttpError:
    print('An error occurred: %s' % error)



def main():
    """Shows basic usage of the Gmail API.

    Creates a Gmail API service object and outputs a list of label names
    of the user's Gmail account.
    """
    credentials = get_credentials()
    http = credentials.authorize(httplib2.Http())
    service = discovery.build('gmail', 'v1', http=http)

    results = service.users().labels().list(userId='me').execute()
    labels = results.get('labels', [])
    msg_att = create_message_with_attachment()
    SendMessage(service, 'me',msg_att)

    # if not labels:
    #     print('No labels found.')
    # else:
    #   print('Labels:')
    #   for label in labels:
    #     print(label['name'])


if __name__ == '__main__':
    main()`

**Comment by mehdirazajaffri** [comment] 2018-01-01 13:30
Google should update its documentation.

**Comment by StevenGann** [comment] 2018-04-17 22:36
@luabr You are my hero. I spent the whole bloody day trying to fix Google's code.

It's a shame Google doesn't care about developers.

**Comment by jonparrott** [comment] 2018-04-17 22:58
I apologize that this has slipped under the radar so long. I'm really glad that @luabr's solution has been able to help those who've found this issue. 

Unfortunately, the people who maintain this library do not maintain those samples. The good news is that we're all at the same company, so I've filed a bug internally with them to update their documentation and samples (internal issue number 78191393)- and I'll happily help them do so.

I'm going to close this issue as there isn't anything actionable *for this library*. I *will* comment here when the internal issue about the documentation is addressed.

Thanks, everyone.

**Closed by jonparrott** 2018-04-17 22:58 UTC
Labels: documentation

**Comment by ofersadan85** [comment] 2018-07-04 11:20
Just reporting that this issue still exists as of July 2018, spent hours trying to fix something that doesn't really need more than 3 minutes of docs corrections to help the users and developers who rely on you... isn't it ridiculous that the people writing the documentation are not the same people maintaining the library with all it's changes and issues? This is again the same feeling I had developing in "Google Apps script"... it seems that both here and there you guys don't **talk** to each other and just file "internal bug reports" that no one ever attends to.

THANK YOU @luabr  for your solution!

**Comment by chris360KS** [comment] 2019-04-12 00:06
Still needs fixing :(

**Comment by melvinkcx** [comment] 2019-10-21 07:55
Just reporting ,this is still happening as of 21 Oct 2019.

**Comment by zen29d** [comment] 2019-12-04 13:18
Still now the same error. I mean, ohh come on google update your docs.
Thanks @cjerdonek

**Comment by busunkim96** [comment] 2019-12-04 14:33
Apologies for all the frustration caused by this. I've pinged the internal bug originally filed by Thea. Thank you for your patience.

**Comment by fw-aaron** [comment] 2020-02-12 14:35
Still an issue in February, 2020. I see this issue is closed which is fine. Where can we keep up-to-date on the progress of the documentation issue?

**Comment by PFython** [comment] 2020-05-21 07:56
Coming somewhat late to the party, but here's my solution if it helps others:

https://stackoverflow.com/a/61929807/7971585

**Comment by iwangu** [comment] 2020-06-05 03:28
@PFython that helped a ton, thx for your most recent post!!

**Comment by karman1102** [comment] 2021-02-03 20:48
Has anyone figured out how to reply to a given thread using thread id?
I tried the code given here [https://stackoverflow.com/questions/58336859/how-to-send-an-existing-email-to-a-new-thread-using-gmail-api](https://stackoverflow.com/questions/58336859/how-to-send-an-existing-email-to-a-new-thread-using-gmail-api). Problem - under the sent mail section, it shows that the email has been replied to whereas it comes as a new mail on the recipient's end.

**Comment by fw-aaron** [comment] 2021-02-04 15:30
@karman1102 I'm not sure what all needs to be in line for e-mails to group together, but I don't think it has anything to do with the e-mail itself. Gmail is grouping them on the recipient's side. I was always under the impression that as long as the subject was exactly the same (minus "Re: ", "Fwd: ", etc.), Gmail would group them (unless there's no subject). I've had this happen to me when it's not desired (accidentally-matching subjects like "Invoice"). That stack exchange question and answer certainly seem to suggest a "thread id" :man_shrugging: .

**Comment by karman1102** [comment] 2021-02-04 19:28
@fw-aaron The use of thread id and subject had been mentioned in the official documentation as well. I wonder if anyone has accomplished the 'grouping' together of mails on the recipient's side.

What I wish to accomplish is - replying from Gmail API to a mail such that it appears as a 'replied-to' mail on the recipient's end. That is, grouped together

**Comment by ashwinsr** [comment] 2021-05-04 22:05
Same issue in May 2021!

**Comment by vinit1** [comment] 2021-05-22 18:47
Yes, I faced the same issue in May 2021!
Thanks @cjerdonek!
