### ISSUE TITLE
Not getting API v2 properties (drive.files.list)

### ISSUE THREAD

**Issue by pferate** [google/google-api-python-client#150] opened 2015-10-21 21:13 UTC
When getting the metadata of `File` objects from a `FileList`, I'm only seeing the properties from v1 of the API, even though I am specifying v2.  It almost looks like Google's API service is sending the wrong response back, but I could be wrong.

Not sure if it helps at all, but the `selfLink` property references the v2 address of the file.

Below is a simple test case that shows this (I don't have permission to attach a document here).

``` python
import apiclient
import httplib2
from oauth2client.file import Storage

storage = Storage('/path/to/cred_file.cred')
credentials = storage.get()

http = httplib2.Http()
http = credentials.authorize(http)

service = apiclient.discovery.build("drive", "v2", http=http)

metadata = service.files().list().execute()

print("service._baseUrl:                 ", service._baseUrl)
print("metadata['items'][0]['selfLink']: ", metadata['items'][0]['selfLink'])
print("metadata['items'][0].keys():      ", metadata['items'][0].keys())

# Is the service base URL v2 of the API?
assert service._baseUrl == 'https://www.googleapis.com/drive/v2/'
# Does the self link use v2 of the API?
assert 'https://www.googleapis.com/drive/v2/' in metadata['items'][0]['selfLink']
# Available in both v1 and v2 of API
assert 'userPermission' in metadata['items'][0]
# Only available in v2 of API
assert 'permissions' in metadata['items'][0] # Fails

```

I don't know if this is something that needs to be [reported to the Apps API Team](https://code.google.com/a/google.com/p/apps-api-issues/issues/entry?template=Defect%20report) or not.

**Comment by nathanielmanistaatgoogle** [comment] 2015-10-21 21:33
Elaborate more on how you could be wrong? How much additional work would I have to ask of you to be confident that the problem were with Google's API service?

**Comment by pferate** [comment] 2015-10-21 22:01
I was thinking that there

**Comment by pferate** [comment] 2015-10-22 00:13
It looks like I'm seeing the v2 properties, but am missing many of them.

I [opened a ticket](https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=4110) for the API Team.

**Comment by nathanielmanistaatgoogle** [comment] 2015-10-22 00:14
Great. Will keep listening here in case anything comes back to this library.

**Comment by pferate** [comment] 2015-10-22 02:32
Looking at some of the other issues posted there, it looks like there has been a 2-3 month delay between initial filing and somebody responding or categorizing them; issues from June/July getting a response or categorized in late Sept or early Oct.

**Comment by nathanielmanistaatgoogle** [comment] 2016-03-18 22:17
@pferate: should this issue remain open?

**Comment by bantini** [comment] 2018-01-18 21:38
Closing this issue because the Google Drive API has been updated to v3. Please feel free to open another issue if the problem is detected in the new API.

**Closed by bantini** 2018-01-18 21:38 UTC
