### ISSUE TITLE
Import Google API Python is failing

### ISSUE THREAD

**Issue by mbettan** [google/google-api-python-client#136] opened 2015-09-22 07:36 UTC
Hello,

When executing following code through Python 2.7 / Jython on Windows

```
#!/usr/bin/env python
from apiclient import discovery
```

I have following errors which prevent to execute it 

```
Command failed java.lang.RuntimeException: Slang Error : Error executing python
script: Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "C:\cslang\bin\..\python-lib\apiclient\__init__.py", line 19, in <module>

    from googleapiclient import discovery
  File "C:\cslang\bin\..\python-lib\googleapiclient\discovery.py", line 68, in <
module>
    from oauth2client.client import GoogleCredentials
  File "C:\cslang\bin\..\python-lib\oauth2client\client.py", line 1674, in <modu
le>
    _cached_http = httplib2.Http(MemoryCache())
AttributeError: 'module' object has no attribute 'Http'
```

Below are the full logs and cloudslang file
http://we.tl/5GjKRYxKn5

Does google-api-python-client (or dependencies) need Cython ? Any ideas why it's failing when importing

**Comment by nathanielmanistaatgoogle** [comment] 2015-09-22 13:23
On Tue, Sep 22, 2015 at 12:36 AM, Michaël Bettan <notifications@github.com>
wrote:

> When executing following code through Python 2.7 / Jython on Windows
>
> #!/usr/bin/env python
> from apiclient import discovery
>
> I have following errors which prevent to execute it
>
> Command failed java.lang.RuntimeException: Slang Error : Error executing python
> script: Traceback (most recent call last):
>   File "<string>", line 7, in <module>
>   File "C:\cslang\bin\..\python-lib\apiclient\__init__.py", line 19, in <module>
>
>     from googleapiclient import discovery
>   File "C:\cslang\bin\..\python-lib\googleapiclient\discovery.py", line 68, in <
> module>
>     from oauth2client.client import GoogleCredentials
>   File "C:\cslang\bin\..\python-lib\oauth2client\client.py", line 1674, in <modu
> le>
>     _cached_http = httplib2.Http(MemoryCache())
> AttributeError: 'module' object has no attribute 'Http'
>
> Below are the full logs and cloudslang file
> http://we.tl/5GjKRYxKn5
>
> Does google-api-python-client (or dependencies) need Cython ?
>
I'm not seeing anything in what you've posted that suggests that Cython
would be needed?

> Any ideas why it's failing when importing
>
It's failing because the httplib2 module in your Python installation
doesn't have an attribute named "Http". Can you confirm that that's the
case independent of oauth2client by examining the output of something like
"import httplib2; dir(httplib2)" in your Python interpreter? If that's
confirmed to be the problem, how could it be happening?
-N

**Comment by tmatsuo** [comment] 2015-09-22 14:29
I tried to import httplib2 with my jython installation and it fails as follows:

```
tmatsuo:jython$ ~/jython/bin/jython test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from googleapiclient import discovery
  File "/home/tmatsuo/jython/Lib/site-packages/googleapiclient/discovery.py", line 49, in <module>
    import httplib2
  File "/home/tmatsuo/jython/Lib/site-packages/httplib2/__init__.py", line 59, in <module>
    from httplib2 import socks
  File "/home/tmatsuo/jython/Lib/site-packages/httplib2/__init__.py", line 59, in <module>
    from httplib2 import socks
  File "/home/tmatsuo/jython/Lib/site-packages/httplib2/socks.py", line 116, in <module>
    class socksocket(socket.socket):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
```

This happens because `socket.socket` is a class for cython but the socket module in jython is a bit different and `socket.socket` is a function in jython (in other words, because the code tried to subclass a function instead of a class). 

I found an issue on httplib2:
https://github.com/jcgregorio/httplib2/issues/306

If I patch `httplib2/sock.py` as follows
```
# import socket
from socket import socket
```
Then I can successfully import httplib2 now. Can you try this workaround? I'm still wondering why you're getting a different error, but I think it's worth trying.

**Comment by mbettan** [comment] 2015-09-22 16:18
Anyway to avoid Cython usage? Jython is not compatible with Cython apparently.

**Comment by tmatsuo** [comment] 2015-09-22 16:20
The above patch worked for me with Jython. Have you tried it?

**Comment by mbettan** [comment] 2015-09-22 17:19
Yes, I confirm it's fully working now - Thanks

Unfortunately, I can require this fix for each new deployment of my project (https://github.com/CloudSlang/cloud-slang). It relies on pip install which will install the orginal package.

Any way to avoid this import directly from my python script with import command (like an except) ?
Do you advise me to suggest this fix to httplib2 project ?

Thanks for your help, really useful.

**Comment by tmatsuo** [comment] 2015-09-22 17:21
Let's fix httplib2 on Jython. I'll add a comment on https://github.com/jcgregorio/httplib2/issues/306

**Comment by tmatsuo** [comment] 2015-09-22 18:05
There is already a PR for this issue:
https://github.com/jcgregorio/httplib2/pull/300

**Comment by mbettan** [comment] 2015-09-24 22:15
Thanks, that's great.

**Comment by mbettan** [comment] 2015-10-04 03:11
Hello, I have a new error now with the new httplib 0.9.2 library through Jython

```
Command failed java.lang.RuntimeException: Slang Error : Error executing python
script: Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\cslang\bin\..\python-lib\oauth2client\client.py", line 1319, in get_a
pplication_default
    return GoogleCredentials._get_implicit_credentials()
  File "C:\cslang\bin\..\python-lib\oauth2client\client.py", line 1304, in _get_
implicit_credentials
    credentials = checker()
  File "C:\cslang\bin\..\python-lib\oauth2client\client.py", line 1255, in _impl
icit_credentials_from_files
    credentials_filename = _get_environment_variable_file()
  File "C:\cslang\bin\..\python-lib\oauth2client\client.py", line 1399, in _get_
environment_variable_file
    raise ApplicationDefaultCredentialsError(
oauth2client.client.ApplicationDefaultCredentialsError: File C:\Users\bettanm\Do
cuments\GitHub\cloud-slang-content\content\io\cloudslang\cloud_provider\gke\clou
dslang-026ac0ebb6e0.json (pointed by GOOGLE_APPLICATION_CREDENTIALS environment
variable) does not exist!
```

Any idea why ? It should be solved with your fix right ?

Thanks again for all your help

**Comment by mbettan** [comment] 2015-10-04 03:15
Httplib 0.9.2 release solve the issue, thanks for the fix !

**Comment by mbettan** [comment] 2015-10-12 22:29
Hello @tmatsuo - Any update please ? Thanks

**Comment by mbettan** [comment] 2016-01-03 08:43
@tmatsuo - Any chance we are able to not rely on this library ? It seems not very active anymore if you see the  number of issues and comments. They never updates my pull request

**Comment by bantini** [comment] 2018-01-18 23:04
@mbettan Are you still facing this issue? Alternately, does this library solve your problems?

https://github.com/GoogleCloudPlatform/google-cloud-python

**Comment by bantini** [comment] 2018-01-29 22:35
Closing this issue assuming the new library solved the problem.

**Closed by bantini** 2018-01-29 22:35 UTC
