### ISSUE TITLE
HEAD requests returns 503

### ISSUE THREAD

**Issue by intellisense** [google/google-api-python-client#9] opened 2014-05-27 16:37 UTC
This fails with status `503`:

```
response, content = service._http.request(download_url, method='HEAD')
```

While this works:

```
response, content = service._http.request(download_url)
```

Is it not possible to perform `HEAD` request for files whose `downloadUrl` is available in meta?

**Comment by azamouchi** [comment] 2017-03-12 14:15
Same problem for me when using Drive, i want to check if the download_url match an existing audio file before i start to download, i've tried to make a HEAD request to check that the content-type value correspond to (audio/mpeg), and i still  get this 503 status code. 

Any news ?

**Comment by mcdonc** [comment] 2018-06-18 14:54
Attempt to triage this.

I think the downloadUrl field in Drive metadata has gone the way of the dodo since this issue was originally reported. I'm fuzzy on the release history of the various API revisions, but it appears that in 2016, folks seemed to be using API v2, which does not appear have the downloadUrl field, and since then we have moved on to v3, which did not revive it.

I'm going to try to issue HEAD requests against analogous APIs when I find them to see if the 503 issue has followed us around.

**Comment by mcdonc** [comment] 2018-06-18 18:13
If I'm understanding the issue correctly, responses using analogous calls with the HEAD method seem to now return 200.

```
        md = files.get_media(fileId='1SNvRNpfSeA0jM09ylqC1w7qA0wOZUACf')
        md.uri = md.uri.replace('alt=json', 'alt=media')
        response, content = service._http.request(md.uri, method='HEAD')
        print(response)
        print(content)
```

Results in:

```
{'status': '200', 'content-location': u'https://www.googleapis.com/drive/v3/files/1SNvRNpfSeA0jM09ylqC1w7qA0wOZUACf?alt=media', 'content-disposition': 'attachment', 'content-encoding': 'gzip', 'transfer-encoding': 'chunked', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'vary': 'Origin, X-Origin', 'server': 'UploadServer', 'warning': '214 UploadServer gzipped', 'pragma': 'no-cache', 'x-guploader-uploadid': 'AEnB2Up87jv_iRDBKj6LjxsYqETvTa9m3cgD5Nv4pW2z-83yCW2MC4xxHX7Gi9Z5LAbdsFCgKXE64KbnQ85NoiBUGvB8m4PHlw', 'date': 'Mon, 18 Jun 2018 18:10:35 GMT', 'alt-svc': 'quic=":443"; ma=2592000; v="43,42,41,39,35"', 'content-type': 'application/vnd.debian.binary-package'}
```

**Comment by mcdonc** [comment] 2018-06-19 12:59
Note that my rationale for asserting that downloadUrl no longer exists is:

```
files.get(
            fileId='1SNvRNpfSeA0jM09ylqC1w7qA0wOZUACf',
            fields='id,downloadUrl',
            supportsTeamDrives=True,
        ).execute(http=service._http)
```

Produces:

```
Traceback (most recent call last):
  File "quickstart.py", line 47, in <module>
    ).execute(http=service._http)
  File "/home/chrism/projects/gcloud/google-api-python-client/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/chrism/projects/gcloud/google-api-python-client/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v3/files/1SNvRNpfSeA0jM09ylqC1w7qA0wOZUACf?fields=id%2CdownloadUrl&alt=json&supportsTeamDrives=true returned "Invalid field selection downloadUrl">
```

**Comment by tseaver** [comment] 2018-06-19 20:37
The [Drive REST V3 migration guide](https://developers.google.com/drive/api/v3/migration) shows that the `downloadUrl` field is to be replaced with a query string, `?alt=media`, added to the [`files.get` URL](https://developers.google.com/drive/api/v3/reference/files/get) for the file.

**Comment by mcdonc** [comment] 2018-06-21 19:33
I'm going to close this due to the API changing fairly comprehensively since the bug was filed, and because I can't reproduce it in the new API variants.  But if it pops up again, please comment and we can reopen.  Thanks!

**Closed by mcdonc** 2018-06-21 19:33 UTC
Labels: :rotating_light:, priority: p2+, status: will not fix, type: question
