### ISSUE TITLE
Deadlock during token refresh in BatchHttpRequest.execute()

### ISSUE THREAD

**Issue by sintezcs** [google/google-api-python-client#288] opened 2016-10-09 13:49 UTC
### Environment:

OSX 10.11.6 El Capitan
Python 3.5.1
google-api-python-client==1.5.3
oauth2client==3.0.0
pyOpenSSL==16.1.0
### Description

If you are using `ServiceAccountCredentials` with `file.Storage`, and your credentials storage is empty and your first request to Google API is a`BatchHttpRequest` you get a deadlock during the initial access token refresh procedure in [`BatchHttpRequest.execute()`](https://github.com/google/google-api-python-client/blob/master/googleapiclient/http.py#L1409) method.
### Steps to reproduce:
1. Install requirements
2. Enable Google Analytics API in the Google API Console
3. Create Google Service Account credentials
4. Download your private key file and set the corresponding values in test script (`SERVICE_ACCOUNT_EMAIL`, `PRIVATE_KEY_FILENAME`, `PRIVATE_KEY_PASSWORD`)
5. Use the following script to reproduce:

``` python
import httplib2

from googleapiclient.discovery import build
from googleapiclient.http import BatchHttpRequest

from oauth2client.file import Storage
from oauth2client.service_account import ServiceAccountCredentials

SERVICE_ACCOUNT_EMAIL = 'XXXXXX@developer.gserviceaccount.com'
PRIVATE_KEY_FILENAME = 'YOUR_PRIVATE_KEY.p12'
PRIVATE_KEY_PASSWORD = 'YOUR_PRIVATE_KEY_PASSWORD'
# storage file should not exist or be empty
STORAGE_FILENAME = 'google.json'

if __name__ == '__main__':
    print('Start')
    google_credentials = ServiceAccountCredentials.from_p12_keyfile(
        SERVICE_ACCOUNT_EMAIL,
        PRIVATE_KEY_FILENAME,
        PRIVATE_KEY_PASSWORD,
        scopes='https://www.googleapis.com/auth/analytics.readonly')

    storage = Storage(STORAGE_FILENAME)
    google_credentials.set_store(storage)
    http = httplib2.Http()
    http = google_credentials.authorize(http)
    google_service = build('analytics', 'v3', http=http)

    # using the same request just as an example
    req1 = google_service.management().accounts().list()
    req2 = google_service.management().accounts().list()

    def batch_callback(request_id, response, exception):
        print('Batch response received')
        print('request_id:{}\n'.format(request_id))
        print('response:{}\n'.format(response))
        print('exception:{}\n'.format(exception))

    batch = BatchHttpRequest(callback=batch_callback)
    batch.add(req1)
    batch.add(req2)
    print('Executing batch request...')
    batch.execute()
    # We never get here, deadlock happens
    print('Finished')
```

**Comment by mcdonc** [comment] 2018-06-21 15:46
I could not replicate this bug using:

- Ubuntu Linux 18.04
- Python 3.5.5 (virtualenv)
- pyOpenSSL-18.0.0
- oauth2client-4.1.2
- google-api-python-client master

**Comment by mcdonc** [comment] 2018-06-21 19:31
I'm going to close this issue due to an inability to reproduce, but if you need more help, please comment, and we can reopen.  Thanks!

**Closed by mcdonc** 2018-06-21 19:31 UTC
Labels: :rotating_light:, priority: p1, status: will not fix, type: bug
