### ISSUE TITLE
Undefined error: 'Module_six_moves_urllib_parse' object has no attribute 'urlencode'

### ISSUE THREAD

**Issue by gozali** [google/google-api-python-client#100] opened 2015-05-29 08:07 UTC
I tried code sample from https://cloud.google.com/bigquery/authorization, with the environment mentioned below and i got the error.

Environment:
python version 2.7.6
google-api-python-client version 1.4.0
six version 1.4.1

However when i downgraded google-api-python-client to 1.3.2 it works

**Comment by pepedocs** [comment] 2015-07-22 00:49
Hi gozali,

Have you found a fix for this for version 1.4.1 ?  I got the same issue as well.

Cheers,
Pepe

**Comment by gozali** [comment] 2015-07-22 02:58
not yet @pepedocs, downgraded my api client to 1.3.2 since then

**Comment by AusTiNQ** [comment] 2015-08-14 12:00
Also reproduced on latest google-api-python-client - downgrade to 1.3.2 resolved this issue.

**Comment by erickoledadevrel** [comment] 2015-09-11 21:04
The cause of the problem, and the workaround is best explained here: http://stackoverflow.com/a/29666702/702875

The Google APIs Python client library depends on another library called six, which comes pre-installed with Max OSX. The client library needs a newer version however, and although pip installs it Python ends up loading the older version first, leading to the error.

The workaround is to set the system environment variable `PYTHONPATH` to point directly to pip's install directory, so that version of the six module loads first.

    export PYTHONPATH=/Library/Python/2.7/site-packages

You'll need to add that line to you ~/.bashrc file to ensure it's set for each terminal window.

**Comment by ymnoor21** [comment] 2016-04-30 00:46
Adding `export PYTHONPATH=/Library/Python/2.7/site-packages` worked for me.

**Comment by gasabr** [comment] 2016-06-08 12:41
What can I try if adding didn't help?

**Comment by jonparrott** [comment] 2016-06-08 16:44
This is likely due to an outdated version of six on your system. This can happen with OS X system Python because the Apple-provided six library can't be upgraded.

Have you tried using a virtualenv?

**Comment by ohlaylaohoh** [comment] 2017-05-19 20:26
Hi there, I added the PYTHONPATH to bashrc but didn't work. Any idea why?

**Comment by jonparrott** [comment] 2017-05-26 01:46
@ohlaylaohoh I really don't recommend using the PYTHONPATH thing. Please use virtualenv.

**Comment by tuanchauict** [comment] 2017-09-16 23:11
Use `python3` (3.5) and install `google-api-python-client-py3` works for me (also need to change these in `tools.py` of the library

```    s.wfile.write("<html><head><title>Authentication Status</title></head>")
    s.wfile.write("<body><p>The authentication flow has completed.</p>")
    s.wfile.write("</body></html>")```
to
```    s.wfile.write(b"<html><head><title>Authentication Status</title></head>")
    s.wfile.write(b"<body><p>The authentication flow has completed.</p>")
    s.wfile.write(b"</body></html>")```

**Comment by mcdonc** [comment] 2018-06-21 19:36
I'm going to close this, as there are two solutions named above (and the PYTHONPATH one is even in the official docs), however, if you need more help, please comment, and I'll try to provide it.  Thanks!

**Closed by mcdonc** 2018-06-21 19:36 UTC
Labels: :rotating_light:, priority: p2+, status: will not fix, type: question
