### ISSUE TITLE
BatchHttpRequest and google-auth

### ISSUE THREAD

**Issue by sbrieuc** [google/google-api-python-client#375] opened 2017-03-29 16:15 UTC
Hi,

I'm using this client library with google-auth to make calls to several Google APIs (Drive mainly), it works fine however it seems that when using a Batch request it doesn't use the credentials of each request in the batch, only the credentials from the first one.

Which means that when I impersonate two different users in two different requests in the same batch, both requests are made impersonating the first user.

For example here's how I proceed to list the files of two users:

```
creds_one = google.oauth2.service_account.Credentials.from_service_account_file(path_to_json, scopes=scopes, subject='user1@xxx.com')
creds_two = google.oauth2.service_account.Credentials.from_service_account_file(path_to_json, scopes=scopes, subject='user2@xxx.com')

drive_service_one = build('drive', 'v3', credentials=creds_one)
drive_service_two = build('drive', 'v3', credentials=creds_two)

_batch = BatchHttpRequest()
_batch.add(request=drive_service_one.files().list(), request_id='u1')
_batch.add(request=drive_service_two.files().list(), request_id='u2')

_batch.execute()
```

What I observe in this case is that both requests return the list of files from the first user.
Am I missing something here ?

Thanks

**Comment by jonparrott** [comment] 2017-03-29 19:24
@sbrieuc is this perhaps a duplicate of #350?

**Comment by sbrieuc** [comment] 2017-03-29 22:18
@jonparrott Well it doesn't look like it.

To me issue #350 relates to credentials having no valid access token and using oauth2client. From what I can see in my case the issue is specific with using credentials from google-auth library. With oauth2client credentials it works perfectly.

Looking a bit more in the code, when building a service from a credentials object there are two cases:
```
if HAS_GOOGLE_AUTH and isinstance(
            credentials, google.auth.credentials.Credentials):
        return google_auth_httplib2.AuthorizedHttp(credentials,
                                                   http=build_http())
else:
        return credentials.authorize(build_http())
```

1/ If the Credentials object is from oauth2client library, then the authorized http object returned is an Http() instance from httplib2 where the _request_ method has been overridden and on which a _credentials_ attribute is set with the actual credentials provided

```
def authorize(self, http):
        ...
        # The closure that will replace 'httplib2.Http.request'.
        def new_request(uri, method='GET', body=None, headers=None,
                        redirections=httplib2.DEFAULT_MAX_REDIRECTS,
                        connection_type=None):
            ...
            
        # Replace the request method with our own closure.
        http.request = new_request

        # Set credentials as a property of the request method.
        setattr(http.request, 'credentials', self)

        return http
```

2/ If the Credentials object however is from google-auth library, then the authorized http object returned is an instance of AuthorizedHttp. This object has its own _request_ method which does not have a _credentials_ attribute

```
class AuthorizedHttp(object):
    def __init__(self, credentials, http=None,
                 refresh_status_codes=transport.DEFAULT_REFRESH_STATUS_CODES,
                 max_refresh_attempts=transport.DEFAULT_MAX_REFRESH_ATTEMPTS):
        
        if http is None:
            http = _make_default_http()

        self.http = http
        self.credentials = credentials
        self._refresh_status_codes = refresh_status_codes
        self._max_refresh_attempts = max_refresh_attempts
        # Request instance used by internal methods (for example,
        # credentials.refresh).
        self._request = Request(self.http)

    def request(self, uri, method='GET', body=None, headers=None,
                **kwargs):
        ... 
```

Now, when making a regular request, this works fine, as the _request_ method from AuthorizedHttp takes care of refreshing and applying the credentials to the headers.

However In BatchHttpRequest, when serializing requests it works a bit differently from what I can see. The _request_ method from the http object is expected to have a _credentials_ attribute, and only in that case the credentials are applied to the headers. 

```
if request.http is not None and hasattr(request.http.request,
        'credentials'):
      request.http.request.credentials.apply(headers)
```
This is where the issue comes up, as with google-auth the AuthorizedHttp object _request_ method does not have this _credentials_ attribute. Therefore the credentials cannot be applied to the headers and it falls back on using the credentials from the first request in the batch as we can see in the execute() method of BatchHttpRequest:

```
# If http is not supplied use the first valid one given in the requests.
    if http is None:
      for request_id in self._order:
        request = self._requests[request_id]
        if request is not None:
          http = request.http
          break
```

This is as far as I understand what's going on. Maybe I missed something but it seems to me that google-auth credentials are not fully supported in the case of batch request.

**Comment by jonparrott** [comment] 2017-03-30 03:30
Thanks, @sbrieuc. This gives me a good idea of what's going on. It seems to me that google_auth_httplib2 should be modified to support a per-request credentials. I'll look into that.

**Comment by jonparrott** [comment] 2017-03-30 20:17
@sbrieuc can you verify that https://github.com/google/google-api-python-client/pull/376 resolves this issue?

**Comment by sbrieuc** [comment] 2017-03-31 07:49
@jonparrott I made my comments in #376 but it looks like it will solve the issue.

**Closed** 2017-06-20 00:55 UTC
Labels: priority: p2+, status: enhancement
