### ISSUE TITLE
Youtube video uploads of files larger than 64 GB are refused

### ISSUE THREAD

**Issue by NeoTheThird** [google/google-api-python-client#354] opened 2017-02-22 14:47 UTC
The client refuses to upload files bigger than 64GB. Why is that? The Web interface accepts those files and the API should technically be able to handle it. I tried to replace lines 431 and 433 in `/googleapiclient/discovery.py` with `return int(9223372036854775807)` and it works, but this is just a hack of cause. Is there any reason why this limit should not be raised?

This issue was discovered downstream: https://github.com/tokland/youtube-upload/issues/153

**Comment by jonparrott** [comment] 2017-02-22 18:44
The limit actually seems to come from the API itself, see https://github.com/google/google-api-python-client/blob/20af04d379e079b7a70fa493336307e11d6f50dd/googleapiclient/discovery.py#L546

@lukesneeringer any ideas?

**Comment by aaronshaf** [comment] 2017-08-28 17:30
@NeoTheThird Turns out your workaround did not work for me. Stopped at 64gb.

**Comment by mcdonc** [comment] 2018-07-23 16:05
I haven't actually tried uploading a 64+GB file because my connection won't support it at the moment, but the API now returns "5120GB" as the maxSize from discovery using v3 of the API.

```
{'description': 'Creates a new file.',
 'httpMethod': 'POST',
 'id': 'drive.files.create',
 'mediaUpload': {'accept': ['*/*'],
                 'maxSize': '5120GB',
...
```

As a result, I am closing this issue, because I believe this was a server-imposed limitation.  If anyone believes this is in error, please reopen or comment.  Thanks!

**Closed by mcdonc** 2018-07-23 16:05 UTC
Labels: :rotating_light:, priority: p2, status: acknowledged, type: bug

**Comment by CaViCcHi** [comment] 2019-04-16 00:48
> {'description': 'Creates a new file.',
>  'httpMethod': 'POST',
>  'id': 'drive.files.create',
>  'mediaUpload': {'accept': ['*/*'],
>                  'maxSize': '5120GB',

this still seems to be an issue, I think the confusion comes from the fact that we're talking about youtube.insert which should return "128GB" rather than drive.create which does return "5120GB"

**Comment by CaViCcHi** [comment] 2019-04-16 19:19
and I can confirm it doesn't work when uploading to youtube, I tried faking the first method that checks the api maxSize to return 128GB so the upload starts, but after uploading 70GB, at the end of the file the API explodes saying that the maximum upload size is 64GB, just tried last night.

**Comment by busunkim96** [comment] 2019-04-16 19:21
@CaViCcHi, Would you mind opening a new issue and referencing this one? We unfortunately are more likely to miss comments made on older issues.

**Comment by CaViCcHi** [comment] 2019-04-16 19:37
@busunkim96  Done, thanks :)
